---
abstract: "Dist::Zilla configurantion for GABRIEL's projects"
author:
  - 'Gabriel Vieira <gabriel.vieira@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-GABRIEL
requires:
  Dist::Zilla: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/gabrielmad/dist-zilla-pluginbundle-author-gabriel/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-Author-GABRIEL
  repository: git://github.com/gabrielmad/dist-zilla-pluginbundle-author-gabriel.git
version: 0.01
